sudo: required
language: go

go:
- 1.12.x

services:
- docker

addons:
  apt:
    packages:
    - docker-ce
    - parallel

script:
- set -e
- make test-go-fmt
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- dep ensure -vendor-only
- go test -v -race -coverprofile=coverage.txt -covermode=atomic ./pkg/...
- make build test-acceptance
- docker build -t kubesec .
- docker run -dp 8080:8080 kubesec
- sleep 1
- curl -sSX POST --data-binary @test/asset/score-0-daemonset-host-network.yml http://localhost:8080/scan | grep loopback
- curl -sSX POST --data-binary @test/asset/invalid-schema.yml http://localhost:8080/scan | grep Invalid

after_success:
- if [ -z "$DOCKER_USER" ]; then
    echo "Skipping image push! Docker Hub credentials not found";
  else
    BRANCH_COMMIT=$(echo ${TRAVIS_COMMIT} | head -c7);
    docker tag kubesec:latest kubesec/kubesec:${BRANCH_COMMIT};
    echo $DOCKER_PASS | docker login -u=$DOCKER_USER --password-stdin;
    docker push kubesec/kubesec:${BRANCH_COMMIT};
  fi

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    branch: master
    tags: true
